version: '3.8'

services:
    app:
        build: .
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        ports:
            - "8000:80"
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_CONNECTION=pgsql
            - DB_HOST=host.docker.internal
            - DB_PORT=5433
            - DB_DATABASE=dkrburger
            - DB_USERNAME=postgres
            - DB_PASSWORD=admin
            - ASSET_URL=http://localhost:8000
        extra_hosts:
            - "host.docker.internal:host-gateway"  # Important pour Windows
